import {IActivity, ICard, ICategory} from '../Types/types';

export const DummyCards: ICard[] = [
  {
    id: 1,
    cardNumber: '**** **** **** 1071',
    cardHolder: 'Sefa İlyas Öz',
    validThru: '07/23',
    cvv: '***',
    cardType: 'Visa',
    colors: ['rgba(136,98,199,1)', 'rgba(112,91,176,1)', 'rgba(160,100,182,1)'],
  },
  {
    id: 2,
    cardNumber: '**** **** **** 1453',
    cardHolder: 'Sefa İlyas Öz',
    validThru: '10/25',
    cvv: '***',
    cardType: 'Master',
    colors: ['rgba(136,98,199,1)', 'rgba(112,91,176,1)', 'rgba(160,100,182,1)'],
  },
  {
    id: 3,
    cardNumber: '**** **** **** 1453',
    cardHolder: 'Sefa İlyas Öz',
    validThru: '10/25',
    cvv: '***',
    cardType: 'Master',
    colors: ['rgba(136,98,199,1)', 'rgba(112,91,176,1)', 'rgba(160,100,182,1)'],
  },
  {
    id: 4,
    cardNumber: '**** **** **** 1453',
    cardHolder: 'Sefa İlyas Öz',
    validThru: '10/25',
    cvv: '***',
    cardType: 'Master',
    colors: ['rgba(136,98,199,1)', 'rgba(112,91,176,1)', 'rgba(160,100,182,1)'],
  },
  {
    id: 5,
    cardNumber: '**** **** **** 1453',
    cardHolder: 'Sefa İlyas Öz',
    validThru: '10/25',
    cvv: '***',
    cardType: 'Master',
    colors: ['rgba(136,98,199,1)', 'rgba(112,91,176,1)', 'rgba(160,100,182,1)'],
  },
  {
    id: 6,
    cardNumber: '**** **** **** 1453',
    cardHolder: 'Sefa İlyas Öz',
    validThru: '10/25',
    cvv: '***',
    cardType: 'Master',
    colors: ['rgba(136,98,199,1)', 'rgba(112,91,176,1)', 'rgba(160,100,182,1)'],
  },
];

export const Activities: IActivity[] = [
  {
    id: 1,
    description: 'Aralık ayı maaşı',
    type: 'income',
    category: 'salary',
    date: '05.01.2023',
    price: 20000,
    cardId: 1,
  },
  {
    id: 2,
    description: 'Haftalık mutfak alışverişi',
    type: 'expense',
    category: 'kitchen',
    date: '12.01.2023',
    price: 700,
    cardId: 2,
  },
  {
    id: 3,
    description: 'Sonay sürücü kursu taksidi',
    type: 'expense',
    category: 'kitchen',
    date: '20.01.2023',
    price: 1500,
  },
  {
    id: 4,
    description: 'Haftalık mutfak alışverişi',
    type: 'expense',
    category: 'kitchen',
    date: '22.01.2023',
    price: 400,
  },
  {
    id: 5,
    description: 'Freelancing',
    type: 'income',
    category: 'salary',
    date: '22.01.2023',
    price: 15000,
  },
  {
    id: 6,
    description: 'Ocak Ayı Kirası',
    type: 'expense',
    category: 'rent',
    date: '05.01.2023',
    price: 3500,
  },
  {
    id: 7,
    description: 'Ocak Ayı Kredi Ödemesi',
    type: 'expense',
    category: 'credit',
    date: '05.01.2023',
    price: 4990,
  },
  {
    id: 8,
    description: 'Ocak Ayı Kredi Kartı Ödemesi',
    type: 'expense',
    category: 'creditCard',
    date: '05.01.2023',
    price: 8000,
  },
];

// export const ActivityCategoryNames = [
//   {
//     other: 'Diğer',
//     kitchen: 'Mutfak',
//     fun: 'Eğlence',
//     bills: 'Faturalar',
//     salary: 'Maaş',
//     transportation: 'Ulaşım',
//     transaction: 'Para Aktarma',
//     outsource: 'Ek Gelir',
//     rent: 'Kira',
//     creditCard: 'Kredi Kartı',
//     credit: 'Kredi Ödemesi',
//     food: 'Yemek',
//     gasoline: 'Benzin',
//     car: 'Araba',
//   };
// ]

export const ActivityCategoryNames: ICategory[] = [
  {id: 12, key: 'other', value: 'Diğer'},
  {id: 1, key: 'fun', value: 'Eğlence'},
  {id: 2, key: 'bills', value: 'Faturalar'},
  {id: 3, key: 'salary', value: 'Maaş'},
  {id: 4, key: 'transportation', value: 'Ulaşım'},
  {id: 5, key: 'kitchen', value: 'Mutfak'},
  {id: 6, key: 'transaction', value: 'Para Aktarma'},
  {id: 7, key: 'outsource', value: 'Ek Gelir'},
  {id: 8, key: 'rent', value: 'Kira'},
  {id: 9, key: 'creditCard', value: 'Kredi Kartı'},
  {id: 10, key: 'credit', value: 'Kredi'},
  {id: 11, key: 'food', value: 'Yemek'},
  {id: 13, key: 'gasoline', value: 'Benzin'},
  {id: 14, key: 'car', value: 'Araba'},
];
