import {IActivity, ICard, ICategory} from '../Types/types';

export const Activities: IActivity[] = [
  {
    id: 1,
    description: 'Aralık ayı maaşı',
    type: 'income',
    category: 'salary',
    date: '05.01.2023',
    price: 20000,
    cardId: 1,
  },
  {
    id: 2,
    description: 'Haftalık mutfak alışverişi',
    type: 'expense',
    category: 'kitchen',
    date: '12.01.2023',
    price: 700,
    cardId: 2,
  },
  {
    id: 3,
    description: 'Sonay sürücü kursu taksidi',
    type: 'expense',
    category: 'kitchen',
    date: '20.01.2023',
    price: 1500,
  },
  {
    id: 4,
    description: 'Haftalık mutfak alışverişi',
    type: 'expense',
    category: 'kitchen',
    date: '22.01.2023',
    price: 400,
  },
  {
    id: 5,
    description: 'Freelancing',
    type: 'income',
    category: 'salary',
    date: '22.01.2023',
    price: 15000,
  },
  {
    id: 6,
    description: 'Ocak Ayı Kirası',
    type: 'expense',
    category: 'rent',
    date: '05.01.2023',
    price: 3500,
  },
  {
    id: 7,
    description: 'Ocak Ayı Kredi Ödemesi',
    type: 'expense',
    category: 'credit',
    date: '05.01.2023',
    price: 4990,
  },
  {
    id: 8,
    description: 'Ocak Ayı Kredi Kartı Ödemesi',
    type: 'expense',
    category: 'creditCard',
    date: '05.01.2023',
    price: 8000,
  },
];

// export const ActivityCategoryNames = [
//   {
//     other: 'Diğer',
//     kitchen: 'Mutfak',
//     fun: 'Eğlence',
//     bills: 'Faturalar',
//     salary: 'Maaş',
//     transportation: 'Ulaşım',
//     transaction: 'Para Aktarma',
//     outsource: 'Ek Gelir',
//     rent: 'Kira',
//     creditCard: 'Kredi Kartı',
//     credit: 'Kredi Ödemesi',
//     food: 'Yemek',
//     gasoline: 'Benzin',
//     car: 'Araba',
//   };
// ]

export const ActivityCategoryNames: ICategory[] = [
  {id: 12, key: 'Diğer', value: 'Diğer'},
  {id: 1, key: 'Eğlence', value: 'Eğlence'},
  {id: 2, key: 'Faturalar', value: 'Faturalar'},
  {id: 3, key: 'Maaş', value: 'Maaş'},
  {id: 4, key: 'Ulaşım', value: 'Ulaşım'},
  {id: 5, key: 'Mutfak', value: 'Mutfak'},
  {id: 6, key: 'Para', value: 'Para Aktarma'},
  {id: 7, key: 'Ek', value: 'Ek Gelir'},
  {id: 8, key: 'Kira', value: 'Kira'},
  {id: 9, key: 'Kredi', value: 'Kredi Kartı'},
  {id: 10, key: 'Kredi', value: 'Kredi'},
  {id: 11, key: 'Yemek', value: 'Yemek'},
  {id: 13, key: 'Benzin', value: 'Benzin'},
  {id: 14, key: 'Araba', value: 'Araba'},
];
